### ISSUE TITLE
Model override loading breaks when playing with FAPI versions above 85

### ISSUE THREAD

**Issue by Maxmani** [dhyces/trimmed#1]
**Minecraft version:** 1.20.1
**Loader version:** 0.14.22
**Mod version:** 2.1.2

**Describe the bug**
Custom trim material overrides fail to load with errors such as:
```
Unable to load model: 'minecraft:iron_chestplate_arcadiandream-makaite_trim#inventory' referenced from: minecraft:iron_chestplate_arcadiandream-makaite_trim#inventory: java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.impl.client.model.loading.ModelLoadingEventDispatcher.loadModel(net.minecraft.class_2960)" because "this.fabric_eventDispatcher" is null
```
This is due to the old model API getting deprecated. [Relevant discussion here.](https://github.com/orgs/FabricMC/discussions/3214)

I can make this work again in a mod that implements custom armor trim materials using Trimmed, by downgrading the FAPI version and excluding it from any other dependencies. Including the deprecated API seems to do nothing. This works at least until a newer FAPI is installed to the game.

**Comment by dhyces** [comment]
Fixed with 2.1.3
